### ISSUE TITLE
Stripping the Mosin-Nagant's scope creates an invisible item in your hand

### ISSUE THREAD

**Issue by Cartlord** [JasmineRickards/TGMC-PVE#133]
### Description

When replacing my Mosin's scope with another sight, I found I was unable to pick things up wit one hand - and it turned out that was because there was an invisible scope item in it that I had to drop.

### Test Merges

None

### Reproduction Steps

-Buy Mosin
-Strip sight
-Acquire void item

**Comment by DerFlammenwerfer** [comment]
This is probably because the scope doesn't have the correct icon_state or icon defined. I'll take a look.
